Backend/core/urls.py
# Python's Libraries

# DJango's Libraries
from django.urls import path

# Third-party Libraries

# Own's Libraries
from .views import SupplierListView
from .views import SupplierNewView
from .views import SupplierEditView

from .views import SupplierContactListView
from .views import SupplierContactNewView
from .views import SupplierContactEditView

from .views import ClientListView
from .views import ClientNewView
from .views import ClientEditView

from .views import ClientContactListView
from .views import ClientContactNewView
from .views import ClientContactEditView

from .views import ItemListView
from .views import ItemNewView
from .views import ItemEditView
from .views import ItemExportExcel

from .views import WarehouseListView
from .views import WarehouseNewView
from .views import WarehouseEditView
from .views import WarehouseExportExcel
from .views import WarehouseImportExcel
from .views import WarehouseEmptyImportView
from .views import ClientExportExcel
from .views import SupplierContactExportExcel
from .views import ClientContactExportExcel
from .views import StockItemExportExcel
from .views import ClientImportExcel
from .views import ClientEmptyImportView
from .views import ItemImportExcel
from .views import ItemEmptyImportView
from .views import UdmListView
from .views import UdmNewView
from .views import UdmEditView
from .views import SatProductListView
from .views import SatProductNewView
from .views import SatProductEditView
from .views import SupplierExportExcel
from .views import StockItemListView
from .views import StockItemRetrieveView
from .views import SupplierImportExcel
from .views import SupplierEmptyImportView
from .views import SupplierContactImportExcel
from .views import SupplierContactEmptyImportView
from .views import ClientContactImportExcel
from .views import ClientContactEmptyImportView


app_name = 'core'

urlpatterns = [
    path(
        'suppliers/',
        SupplierListView.as_view(),
        name='supplier-list'
    ),
    path(
        'suppliers/new/',
        SupplierNewView.as_view(),
        name='supplier-new'
    ),
    path(
        'suppliers/<int:pk>/edit/',
        SupplierEditView.as_view(),
        name='supplier-edit'
    ),
    path(
        'suppliers/<int:pk>/contactsuppliers/',
        SupplierContactListView.as_view(),
        name='contactsupplier-list'
    ),
    path(
        'suppliers/<int:pk>/contactsuppliers/new/',
        SupplierContactNewView.as_view(),
        name='contactsupplier-new'
    ),
    path(
        'suppliers/export/xlsx/',
        SupplierExportExcel.as_view(),
        name='supplier-export-xlsx'
    ),
    path(
        'suppliers/<int:pk>/suppliercontact/export/xlsx/',
        SupplierContactExportExcel.as_view(),
        name='suppliercontact-export-xlsx'
    ),
    path(
        'contactsuppliers/<int:pk>/edit/',
        SupplierContactEditView.as_view(),
        name='contactsupplier-edit'
    ),
    path(
        'suppliers/import/',
        SupplierImportExcel.as_view(),
        name='supplier-import'
    ),
    path(
        'suppliers/import/empty/',
        SupplierEmptyImportView.as_view(),
        name='supplier-import-empty'
    ),
    path(
        'suppliers/<int:pk>/contactsuppliers/import/',
        SupplierContactImportExcel.as_view(),
        name='contactsupplier-import'
    ),
    path(
        'contactsuppliers/import/empty/',
        SupplierContactEmptyImportView.as_view(),
        name='contactsupplier-import-empty'
    ),
    path(
        'clients/',
        ClientListView.as_view(),
        name='client-list'
    ),
    path(
        'clients/new/',
        ClientNewView.as_view(),
        name='client-new'
    ),
    path(
        'clients/import/',
        ClientImportExcel.as_view(),
        name='clients-import'
    ),
    path(
        'clients/import/empty/',
        ClientEmptyImportView.as_view(),
        name='clients-import-empty'
    ),
    path(
        'clients/<int:pk>/edit/',
        ClientEditView.as_view(),
        name='client-edit'
    ),
    path(
        'clients/<int:pk>/contactclients/',
        ClientContactListView.as_view(),
        name='contactclient-list'
    ),
    path(
        'clients/<int:pk>/contactclients/new/',
        ClientContactNewView.as_view(),
        name='contactclient-new'
    ),
    path(
        'contactclients/<int:pk>/edit/',
        ClientContactEditView.as_view(),
        name='contactclient-edit'
    ),
    path(
        'clients/<int:pk>/contactclients/import/',
        ClientContactImportExcel.as_view(),
        name='contactclient-import'
    ),
    path(
        'contactclients/import/empty/',
        ClientContactEmptyImportView.as_view(),
        name='contactclient-import-empty'
    ),
    path(
        'client/export/xlsx/',
        ClientExportExcel.as_view(),
        name='client-export-xlsx'
    ),
    path(
        'clients/<int:pk>/clientcontact/export/xlsx/',
        ClientContactExportExcel.as_view(),
        name='contactclient-export-xlsx'
    ),
    path(
        'items/',
        ItemListView.as_view(),
        name='item-list'
    ),
    path(
        'items/new/',
        ItemNewView.as_view(),
        name='item-new'
    ),
    path(
        'items/<int:pk>/edit/',
        ItemEditView.as_view(),
        name='item-edit'
    ),
    path(
        'items/xls',
        ItemExportExcel.as_view(),
        name='item-list-xls'
    ),
    path(
        'items/import/',
        ItemImportExcel.as_view(),
        name='items-import'
    ),
    path(
        'items/import/empty/',
        ItemEmptyImportView.as_view(),
        name='items-import-empty'
    ),
    path(
        'warehouses/',
        WarehouseListView.as_view(),
        name='warehouse-list'
    ),
    path(
        'warehouses/new/',
        WarehouseNewView.as_view(),
        name='warehouse-new'
    ),
    path(
        'warehouses/<int:pk>/edit/',
        WarehouseEditView.as_view(),
        name='warehouse-edit'
    ),
    path(
        'warehouses/xls',
        WarehouseExportExcel.as_view(),
        name='warehouse-list-xls'
    ),
    path(
        'warehouses/import/',
        WarehouseImportExcel.as_view(),
        name='warehouses-import'
    ),
    path(
        'warehouses/import/empty/',
        WarehouseEmptyImportView.as_view(),
        name='warehouses-import-empty'
    ),
    path(
        'udm/',
        UdmListView.as_view(),
        name='udm-list'
    ),
    path(
        'udm/new/',
        UdmNewView.as_view(),
        name='udm-new'
    ),
    path(
        'udm/<int:pk>/edit/',
        UdmEditView.as_view(),
        name='udm-edit'
    ),
    path(
        'satproduct/',
        SatProductListView.as_view(),
        name='satproduct-list'
    ),
    path(
        'satproduct/new/',
        SatProductNewView.as_view(),
        name='satproduct-new'
    ),
    path(
        'satproduct/<int:pk>/edit/',
        SatProductEditView.as_view(),
        name='satproduct-edit'
    ),
    path(
        'stockitems/',
        StockItemListView.as_view(),
        name='stockitem-list',
    ),
    path(
        'stockitems/export/xlsx/',
        StockItemExportExcel.as_view(),
        name='stockitems-export-xlsx'
    ),
    path(
        'stockitems/<int:pk>/retrieve/',
        StockItemRetrieveView.as_view(),
        name='stockitem-retrieve',
    ),
]

Backend/home/urls.py
# Django's Libraries
from django.urls import path
from django.urls import re_path
from django.contrib.auth.views import LogoutView

# Own's Libraries
from .views import ActivationConfirmView
from .views import ActivationDoneView
from .views import DashboardView
from .views import LoginView
from .views import StartView
from .views import ProfileDetailView
from .views import ProfilePasswordView
from .views import PasswordForgotView
from .views import PasswordRequestView
from .views import PasswordResetView
from .views import PasswordDoneView
from .views import ProfileDetailView
from .views import ProfilePasswordView
from .views import SettingsView
from .views import TermsView
from .views import QuestionsView
from .views import PrivacityView

app_name = 'home'

urlpatterns = [
    path(
        '',
        LoginView.as_view(),
        name="login"
    ),
    path(
        'terms/',
        TermsView.as_view(),
        name="terms"
    ),
    path(
        'questions/',
        QuestionsView.as_view(),
        name="questions"
    ),
    path(
        'privacity/',
        PrivacityView.as_view(),
        name="privacity"),
    path(
        'dashboard/',
        DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name="logout"
    ),
    path(
        'start/',
        StartView.as_view(),
        name="start"
    ),
    path(
        'settings/',
        SettingsView.as_view(),
        name="settings"
    ),
    path(
        'profile/<int:pk>/detail/',
        ProfileDetailView.as_view(),
        name="profile-detail"
    ),
    path(
        'profile/<int:pk>/password/',
        ProfilePasswordView.as_view(),
        name="profile-password"
    ),
    path(
        'password/forgot/',
        PasswordForgotView.as_view(),
        name="password-forgot"
    ),
    path(
        'password/request/',
        PasswordRequestView.as_view(),
        name="password-request"
    ),
    re_path(
        r'password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetView.as_view(),
        name='password-reset'
    ),
    path(
        'password/done/',
        PasswordDoneView.as_view(),
        name='password-done'
    ),
    re_path(
        r'activation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ActivationConfirmView.as_view(),
        name='activation-confirm'
    ),
    path(
        'activation/done/',
        ActivationDoneView.as_view(),
        name='activation-done'
    )
]

Frontend/src/templates/home/profile/password/profile_password.html
{% extends "master/in/master_in.html" %}
{% load static %}
{% load tags_forms %}
{% load tags_feedback %}
{% load tags_fields %}

{% block title %}
    {{ page_title }}
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'build/home_profile_password.min.css' %}">
{% endblock css %}

{% block content %}
<form class="content" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="content-header">
        <div class="title-main">
            {{page_title}}
        </div>

        <div class="toolbar">
            <div class="toolbar-right">
                <a class="toolbar-right__item" href="{% url 'home:profile-detail' USER.pk %}">
                    <span class="item-icon">
                        <i class="fas fa-user-check"></i>
                    </span>
                    <span class="item-text">
                        Perfil
                    </span>
                </a>
                <a class="toolbar-right__item active" href="{% url 'home:profile-password' USER.pk %}">
                    <span class="item-icon">
                        <i class="fas fa-key"></i>
                    </span>
                    <span class="item-text">
                        Contraseña
                    </span>
                </a>
            </div>
        </div>

        {% tag_messages messages %}
    </div>

    <div class="content-body">

        <div class="content-body__section">

            <div class="card-form">
                <div class="card-form-header">
                    En esta pagina puede cambiar su actual contraseña
                </div>
                <div class="card-form-body">
                    {% tag_messages messages %}
                    {% tag_form_errors form %}
                    {% tag_field_text form.password1 _size="x2" %}
                    {% tag_field_text form.password2 _size="x2" %}
                </div>
            </div>
        </div>

        <div class="content-body__aside">
            <div class="card-aside">
                <div class="card-aside-header">
                    Detalle:
                </div>
                <div class="card-aside-body">
                    {% tag_card_aside_body_item_date "Creado el:" form.user.date_joined %}
                    {% tag_card_aside_body_item_date "Ultimo Login:" form.user.last_login %}
                </div>
            </div>
        </div>

    </div>

    {% tag_card_form_controls True %}

</form>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'build/home_profile_password.min.js' %}"></script>
{% endblock scripts %}